#!/usr/bin/env python3
"""
Train the ride-pricing Random Forest and export every tree as a tiny
JSON-shaped TypeScript module the React Native app imports directly.
This is what makes the "ML" run on-device with no server.

Usage (host):
    docker run --rm -v "$(pwd):/work" -w /work ridepro-ml-api \
        python train_export.py

Output: utils/mlModel.ts
"""

import json
import os
import random

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor

OUT_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "utils", "mlModel.ts")

# --- 1. Synthetic data (mirrors ml_server.py) ---
np.random.seed(42)
random.seed(42)

NUM_SAMPLES = 5000
WEATHER_MAP = {"Clear": 0, "Rain": 1, "Storm": 2, "Fog": 3}
DEMAND_MAP = {"Low": 0, "Normal": 1, "High": 2, "Surge": 3}

rows = []
for _ in range(NUM_SAMPLES):
    distance = round(random.uniform(1.0, 50.0), 2)
    hour = random.randint(0, 23)
    weather = random.choice(list(WEATHER_MAP.keys()))
    demand = random.choice(list(DEMAND_MAP.keys()))

    base = 50 + (distance * 15) + (distance * 3 * 2)
    price = base
    if 8 <= hour <= 10 or 17 <= hour <= 20:
        price *= 1.4
    elif hour >= 23 or hour <= 4:
        price *= 1.25
    if weather == "Rain":
        price *= 1.3
    elif weather == "Storm":
        price *= 1.8
    elif weather == "Fog":
        price *= 1.2
    if demand == "Low":
        price *= 0.85
    elif demand == "High":
        price *= 1.2
    elif demand == "Surge":
        price *= 1.6
    noise = (random.random() * 0.08) - 0.04
    rows.append([distance, hour, WEATHER_MAP[weather], DEMAND_MAP[demand], max(50.0, price * (1 + noise))])

df = pd.DataFrame(rows, columns=["distanceKm", "timeOfDayHour", "weather", "demandLevel", "price"])

# --- 2. Train a small forest (small enough to ship inside the app bundle) ---
print("Training Random Forest (30 trees, depth=6)...")
model = RandomForestRegressor(n_estimators=30, max_depth=6, random_state=42)
X = df[["distanceKm", "timeOfDayHour", "weather", "demandLevel"]].to_numpy()
y = df["price"].to_numpy()
model.fit(X, y)
score = model.score(X, y)
print(f"R^2 on training data: {score:.4f}")

# --- 3. Export every tree as a flat JSON-friendly structure ---
trees = []
for est in model.estimators_:
    t = est.tree_
    trees.append(
        {
            "f": [int(x) for x in t.feature.tolist()],          # split feature index per node (-2 for leaves)
            "th": [round(float(x), 4) for x in t.threshold.tolist()],  # split threshold
            "l": [int(x) for x in t.children_left.tolist()],     # left child index (-1 for leaves)
            "r": [int(x) for x in t.children_right.tolist()],    # right child index
            # value is shape (n_nodes, 1, 1) for single-target regression — flatten and round
            "v": [round(float(v), 2) for v in t.value.flatten().tolist()],
        }
    )

bundle = {
    "version": 1,
    "trainedAt": pd.Timestamp.utcnow().isoformat(),
    "featureOrder": ["distanceKm", "timeOfDayHour", "weather", "demandLevel"],
    "weatherMap": WEATHER_MAP,
    "demandMap": DEMAND_MAP,
    "trees": trees,
}

ts = (
    "// AUTO-GENERATED by train_export.py — do not edit by hand.\n"
    "// Random Forest exported as flat arrays so the React Native bundle stays small.\n"
    "// Re-run: `docker run --rm -v \"$(pwd):/work\" -w /work ridepro-ml-api python train_export.py`\n\n"
    "export type RFTree = { f: number[]; th: number[]; l: number[]; r: number[]; v: number[] };\n"
    "export type MLModel = {\n"
    "  version: number;\n"
    "  trainedAt: string;\n"
    "  featureOrder: string[];\n"
    "  weatherMap: Record<string, number>;\n"
    "  demandMap: Record<string, number>;\n"
    "  trees: RFTree[];\n"
    "};\n\n"
    "export const mlModel: MLModel = "
    + json.dumps(bundle, separators=(",", ":"))
    + ";\n"
)

os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
with open(OUT_PATH, "w") as fh:
    fh.write(ts)

size_kb = os.path.getsize(OUT_PATH) / 1024
print(f"Wrote {OUT_PATH} ({size_kb:.1f} KB)")
